local d = (import 'github.com/jsonnet-libs/docsonnet/doc-util/main.libsonnet');
{
  '#':: d.pkg(name='google', url='', help='The `google` package contains functions and utilities for setting up the provider, resources, and data\nsources of the [google Terraform provider](TODO) using Jsonnet.\n\nThis package is autogenerated from the [tf-libsonnet/libgenerator](https://github.com/tf-libsonnet/libgenerator)\nproject.\n'),
  provider: (import 'provider_google.libsonnet'),
  data: (import 'data/main.libsonnet'),
} + (import 'resources/main.libsonnet')
