local tf = (import 'github.com/tf-libsonnet/core/main.libsonnet');
local d = (import 'github.com/jsonnet-libs/docsonnet/doc-util/main.libsonnet');
{
  '#':: d.pkg(name='provider', url='', help='`provider` represents the `google` Terraform provider config.\n\n\n\nThis package contains functions and utilities for setting up the provider using Jsonnet code.\n'),
  '#new':: d.fn(help='\n`google.provider.new` injects a new `google` Terraform `provider`\nblock into the root module document.\n\nOptionally, this inserts the provider into the\n[required_providers](https://developer.hashicorp.com/terraform/language/providers/requirements) `terraform` sub block if\nthe `src` and/or `version` parameters are set.\n\n**Args**:\n  - `access_approval_custom_endpoint` (`string`): Set the `access_approval_custom_endpoint` field on the resulting provider block. When `null`, the `access_approval_custom_endpoint` field will be omitted from the resulting object.\n  - `access_context_manager_custom_endpoint` (`string`): Set the `access_context_manager_custom_endpoint` field on the resulting provider block. When `null`, the `access_context_manager_custom_endpoint` field will be omitted from the resulting object.\n  - `access_token` (`string`): Set the `access_token` field on the resulting provider block. When `null`, the `access_token` field will be omitted from the resulting object.\n  - `active_directory_custom_endpoint` (`string`): Set the `active_directory_custom_endpoint` field on the resulting provider block. When `null`, the `active_directory_custom_endpoint` field will be omitted from the resulting object.\n  - `alloydb_custom_endpoint` (`string`): Set the `alloydb_custom_endpoint` field on the resulting provider block. When `null`, the `alloydb_custom_endpoint` field will be omitted from the resulting object.\n  - `apigee_custom_endpoint` (`string`): Set the `apigee_custom_endpoint` field on the resulting provider block. When `null`, the `apigee_custom_endpoint` field will be omitted from the resulting object.\n  - `apikeys_custom_endpoint` (`string`): Set the `apikeys_custom_endpoint` field on the resulting provider block. When `null`, the `apikeys_custom_endpoint` field will be omitted from the resulting object.\n  - `app_engine_custom_endpoint` (`string`): Set the `app_engine_custom_endpoint` field on the resulting provider block. When `null`, the `app_engine_custom_endpoint` field will be omitted from the resulting object.\n  - `artifact_registry_custom_endpoint` (`string`): Set the `artifact_registry_custom_endpoint` field on the resulting provider block. When `null`, the `artifact_registry_custom_endpoint` field will be omitted from the resulting object.\n  - `assured_workloads_custom_endpoint` (`string`): Set the `assured_workloads_custom_endpoint` field on the resulting provider block. When `null`, the `assured_workloads_custom_endpoint` field will be omitted from the resulting object.\n  - `beyondcorp_custom_endpoint` (`string`): Set the `beyondcorp_custom_endpoint` field on the resulting provider block. When `null`, the `beyondcorp_custom_endpoint` field will be omitted from the resulting object.\n  - `big_query_custom_endpoint` (`string`): Set the `big_query_custom_endpoint` field on the resulting provider block. When `null`, the `big_query_custom_endpoint` field will be omitted from the resulting object.\n  - `biglake_custom_endpoint` (`string`): Set the `biglake_custom_endpoint` field on the resulting provider block. When `null`, the `biglake_custom_endpoint` field will be omitted from the resulting object.\n  - `bigquery_analytics_hub_custom_endpoint` (`string`): Set the `bigquery_analytics_hub_custom_endpoint` field on the resulting provider block. When `null`, the `bigquery_analytics_hub_custom_endpoint` field will be omitted from the resulting object.\n  - `bigquery_connection_custom_endpoint` (`string`): Set the `bigquery_connection_custom_endpoint` field on the resulting provider block. When `null`, the `bigquery_connection_custom_endpoint` field will be omitted from the resulting object.\n  - `bigquery_data_transfer_custom_endpoint` (`string`): Set the `bigquery_data_transfer_custom_endpoint` field on the resulting provider block. When `null`, the `bigquery_data_transfer_custom_endpoint` field will be omitted from the resulting object.\n  - `bigquery_datapolicy_custom_endpoint` (`string`): Set the `bigquery_datapolicy_custom_endpoint` field on the resulting provider block. When `null`, the `bigquery_datapolicy_custom_endpoint` field will be omitted from the resulting object.\n  - `bigquery_reservation_custom_endpoint` (`string`): Set the `bigquery_reservation_custom_endpoint` field on the resulting provider block. When `null`, the `bigquery_reservation_custom_endpoint` field will be omitted from the resulting object.\n  - `bigtable_custom_endpoint` (`string`): Set the `bigtable_custom_endpoint` field on the resulting provider block. When `null`, the `bigtable_custom_endpoint` field will be omitted from the resulting object.\n  - `billing_custom_endpoint` (`string`): Set the `billing_custom_endpoint` field on the resulting provider block. When `null`, the `billing_custom_endpoint` field will be omitted from the resulting object.\n  - `billing_project` (`string`): Set the `billing_project` field on the resulting provider block. When `null`, the `billing_project` field will be omitted from the resulting object.\n  - `binary_authorization_custom_endpoint` (`string`): Set the `binary_authorization_custom_endpoint` field on the resulting provider block. When `null`, the `binary_authorization_custom_endpoint` field will be omitted from the resulting object.\n  - `certificate_manager_custom_endpoint` (`string`): Set the `certificate_manager_custom_endpoint` field on the resulting provider block. When `null`, the `certificate_manager_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_asset_custom_endpoint` (`string`): Set the `cloud_asset_custom_endpoint` field on the resulting provider block. When `null`, the `cloud_asset_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_billing_custom_endpoint` (`string`): Set the `cloud_billing_custom_endpoint` field on the resulting provider block. When `null`, the `cloud_billing_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_build_custom_endpoint` (`string`): Set the `cloud_build_custom_endpoint` field on the resulting provider block. When `null`, the `cloud_build_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_build_worker_pool_custom_endpoint` (`string`): Set the `cloud_build_worker_pool_custom_endpoint` field on the resulting provider block. When `null`, the `cloud_build_worker_pool_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_functions_custom_endpoint` (`string`): Set the `cloud_functions_custom_endpoint` field on the resulting provider block. When `null`, the `cloud_functions_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_identity_custom_endpoint` (`string`): Set the `cloud_identity_custom_endpoint` field on the resulting provider block. When `null`, the `cloud_identity_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_ids_custom_endpoint` (`string`): Set the `cloud_ids_custom_endpoint` field on the resulting provider block. When `null`, the `cloud_ids_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_resource_manager_custom_endpoint` (`string`): Set the `cloud_resource_manager_custom_endpoint` field on the resulting provider block. When `null`, the `cloud_resource_manager_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_run_custom_endpoint` (`string`): Set the `cloud_run_custom_endpoint` field on the resulting provider block. When `null`, the `cloud_run_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_run_v2_custom_endpoint` (`string`): Set the `cloud_run_v2_custom_endpoint` field on the resulting provider block. When `null`, the `cloud_run_v2_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_scheduler_custom_endpoint` (`string`): Set the `cloud_scheduler_custom_endpoint` field on the resulting provider block. When `null`, the `cloud_scheduler_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_tasks_custom_endpoint` (`string`): Set the `cloud_tasks_custom_endpoint` field on the resulting provider block. When `null`, the `cloud_tasks_custom_endpoint` field will be omitted from the resulting object.\n  - `cloudbuildv2_custom_endpoint` (`string`): Set the `cloudbuildv2_custom_endpoint` field on the resulting provider block. When `null`, the `cloudbuildv2_custom_endpoint` field will be omitted from the resulting object.\n  - `clouddeploy_custom_endpoint` (`string`): Set the `clouddeploy_custom_endpoint` field on the resulting provider block. When `null`, the `clouddeploy_custom_endpoint` field will be omitted from the resulting object.\n  - `cloudfunctions2_custom_endpoint` (`string`): Set the `cloudfunctions2_custom_endpoint` field on the resulting provider block. When `null`, the `cloudfunctions2_custom_endpoint` field will be omitted from the resulting object.\n  - `composer_custom_endpoint` (`string`): Set the `composer_custom_endpoint` field on the resulting provider block. When `null`, the `composer_custom_endpoint` field will be omitted from the resulting object.\n  - `compute_custom_endpoint` (`string`): Set the `compute_custom_endpoint` field on the resulting provider block. When `null`, the `compute_custom_endpoint` field will be omitted from the resulting object.\n  - `container_analysis_custom_endpoint` (`string`): Set the `container_analysis_custom_endpoint` field on the resulting provider block. When `null`, the `container_analysis_custom_endpoint` field will be omitted from the resulting object.\n  - `container_attached_custom_endpoint` (`string`): Set the `container_attached_custom_endpoint` field on the resulting provider block. When `null`, the `container_attached_custom_endpoint` field will be omitted from the resulting object.\n  - `container_aws_custom_endpoint` (`string`): Set the `container_aws_custom_endpoint` field on the resulting provider block. When `null`, the `container_aws_custom_endpoint` field will be omitted from the resulting object.\n  - `container_azure_custom_endpoint` (`string`): Set the `container_azure_custom_endpoint` field on the resulting provider block. When `null`, the `container_azure_custom_endpoint` field will be omitted from the resulting object.\n  - `container_custom_endpoint` (`string`): Set the `container_custom_endpoint` field on the resulting provider block. When `null`, the `container_custom_endpoint` field will be omitted from the resulting object.\n  - `core_billing_custom_endpoint` (`string`): Set the `core_billing_custom_endpoint` field on the resulting provider block. When `null`, the `core_billing_custom_endpoint` field will be omitted from the resulting object.\n  - `credentials` (`string`): Set the `credentials` field on the resulting provider block. When `null`, the `credentials` field will be omitted from the resulting object.\n  - `data_catalog_custom_endpoint` (`string`): Set the `data_catalog_custom_endpoint` field on the resulting provider block. When `null`, the `data_catalog_custom_endpoint` field will be omitted from the resulting object.\n  - `data_fusion_custom_endpoint` (`string`): Set the `data_fusion_custom_endpoint` field on the resulting provider block. When `null`, the `data_fusion_custom_endpoint` field will be omitted from the resulting object.\n  - `data_loss_prevention_custom_endpoint` (`string`): Set the `data_loss_prevention_custom_endpoint` field on the resulting provider block. When `null`, the `data_loss_prevention_custom_endpoint` field will be omitted from the resulting object.\n  - `data_pipeline_custom_endpoint` (`string`): Set the `data_pipeline_custom_endpoint` field on the resulting provider block. When `null`, the `data_pipeline_custom_endpoint` field will be omitted from the resulting object.\n  - `database_migration_service_custom_endpoint` (`string`): Set the `database_migration_service_custom_endpoint` field on the resulting provider block. When `null`, the `database_migration_service_custom_endpoint` field will be omitted from the resulting object.\n  - `dataflow_custom_endpoint` (`string`): Set the `dataflow_custom_endpoint` field on the resulting provider block. When `null`, the `dataflow_custom_endpoint` field will be omitted from the resulting object.\n  - `dataplex_custom_endpoint` (`string`): Set the `dataplex_custom_endpoint` field on the resulting provider block. When `null`, the `dataplex_custom_endpoint` field will be omitted from the resulting object.\n  - `dataproc_custom_endpoint` (`string`): Set the `dataproc_custom_endpoint` field on the resulting provider block. When `null`, the `dataproc_custom_endpoint` field will be omitted from the resulting object.\n  - `dataproc_metastore_custom_endpoint` (`string`): Set the `dataproc_metastore_custom_endpoint` field on the resulting provider block. When `null`, the `dataproc_metastore_custom_endpoint` field will be omitted from the resulting object.\n  - `datastore_custom_endpoint` (`string`): Set the `datastore_custom_endpoint` field on the resulting provider block. When `null`, the `datastore_custom_endpoint` field will be omitted from the resulting object.\n  - `datastream_custom_endpoint` (`string`): Set the `datastream_custom_endpoint` field on the resulting provider block. When `null`, the `datastream_custom_endpoint` field will be omitted from the resulting object.\n  - `default_labels` (`obj`): Set the `default_labels` field on the resulting provider block. When `null`, the `default_labels` field will be omitted from the resulting object.\n  - `deployment_manager_custom_endpoint` (`string`): Set the `deployment_manager_custom_endpoint` field on the resulting provider block. When `null`, the `deployment_manager_custom_endpoint` field will be omitted from the resulting object.\n  - `dialogflow_custom_endpoint` (`string`): Set the `dialogflow_custom_endpoint` field on the resulting provider block. When `null`, the `dialogflow_custom_endpoint` field will be omitted from the resulting object.\n  - `dialogflow_cx_custom_endpoint` (`string`): Set the `dialogflow_cx_custom_endpoint` field on the resulting provider block. When `null`, the `dialogflow_cx_custom_endpoint` field will be omitted from the resulting object.\n  - `dns_custom_endpoint` (`string`): Set the `dns_custom_endpoint` field on the resulting provider block. When `null`, the `dns_custom_endpoint` field will be omitted from the resulting object.\n  - `document_ai_custom_endpoint` (`string`): Set the `document_ai_custom_endpoint` field on the resulting provider block. When `null`, the `document_ai_custom_endpoint` field will be omitted from the resulting object.\n  - `document_ai_warehouse_custom_endpoint` (`string`): Set the `document_ai_warehouse_custom_endpoint` field on the resulting provider block. When `null`, the `document_ai_warehouse_custom_endpoint` field will be omitted from the resulting object.\n  - `edgecontainer_custom_endpoint` (`string`): Set the `edgecontainer_custom_endpoint` field on the resulting provider block. When `null`, the `edgecontainer_custom_endpoint` field will be omitted from the resulting object.\n  - `edgenetwork_custom_endpoint` (`string`): Set the `edgenetwork_custom_endpoint` field on the resulting provider block. When `null`, the `edgenetwork_custom_endpoint` field will be omitted from the resulting object.\n  - `essential_contacts_custom_endpoint` (`string`): Set the `essential_contacts_custom_endpoint` field on the resulting provider block. When `null`, the `essential_contacts_custom_endpoint` field will be omitted from the resulting object.\n  - `eventarc_custom_endpoint` (`string`): Set the `eventarc_custom_endpoint` field on the resulting provider block. When `null`, the `eventarc_custom_endpoint` field will be omitted from the resulting object.\n  - `filestore_custom_endpoint` (`string`): Set the `filestore_custom_endpoint` field on the resulting provider block. When `null`, the `filestore_custom_endpoint` field will be omitted from the resulting object.\n  - `firebaserules_custom_endpoint` (`string`): Set the `firebaserules_custom_endpoint` field on the resulting provider block. When `null`, the `firebaserules_custom_endpoint` field will be omitted from the resulting object.\n  - `firestore_custom_endpoint` (`string`): Set the `firestore_custom_endpoint` field on the resulting provider block. When `null`, the `firestore_custom_endpoint` field will be omitted from the resulting object.\n  - `gke_backup_custom_endpoint` (`string`): Set the `gke_backup_custom_endpoint` field on the resulting provider block. When `null`, the `gke_backup_custom_endpoint` field will be omitted from the resulting object.\n  - `gke_hub2_custom_endpoint` (`string`): Set the `gke_hub2_custom_endpoint` field on the resulting provider block. When `null`, the `gke_hub2_custom_endpoint` field will be omitted from the resulting object.\n  - `gke_hub_custom_endpoint` (`string`): Set the `gke_hub_custom_endpoint` field on the resulting provider block. When `null`, the `gke_hub_custom_endpoint` field will be omitted from the resulting object.\n  - `gkehub_feature_custom_endpoint` (`string`): Set the `gkehub_feature_custom_endpoint` field on the resulting provider block. When `null`, the `gkehub_feature_custom_endpoint` field will be omitted from the resulting object.\n  - `gkeonprem_custom_endpoint` (`string`): Set the `gkeonprem_custom_endpoint` field on the resulting provider block. When `null`, the `gkeonprem_custom_endpoint` field will be omitted from the resulting object.\n  - `healthcare_custom_endpoint` (`string`): Set the `healthcare_custom_endpoint` field on the resulting provider block. When `null`, the `healthcare_custom_endpoint` field will be omitted from the resulting object.\n  - `iam2_custom_endpoint` (`string`): Set the `iam2_custom_endpoint` field on the resulting provider block. When `null`, the `iam2_custom_endpoint` field will be omitted from the resulting object.\n  - `iam_beta_custom_endpoint` (`string`): Set the `iam_beta_custom_endpoint` field on the resulting provider block. When `null`, the `iam_beta_custom_endpoint` field will be omitted from the resulting object.\n  - `iam_credentials_custom_endpoint` (`string`): Set the `iam_credentials_custom_endpoint` field on the resulting provider block. When `null`, the `iam_credentials_custom_endpoint` field will be omitted from the resulting object.\n  - `iam_custom_endpoint` (`string`): Set the `iam_custom_endpoint` field on the resulting provider block. When `null`, the `iam_custom_endpoint` field will be omitted from the resulting object.\n  - `iam_workforce_pool_custom_endpoint` (`string`): Set the `iam_workforce_pool_custom_endpoint` field on the resulting provider block. When `null`, the `iam_workforce_pool_custom_endpoint` field will be omitted from the resulting object.\n  - `iap_custom_endpoint` (`string`): Set the `iap_custom_endpoint` field on the resulting provider block. When `null`, the `iap_custom_endpoint` field will be omitted from the resulting object.\n  - `identity_platform_custom_endpoint` (`string`): Set the `identity_platform_custom_endpoint` field on the resulting provider block. When `null`, the `identity_platform_custom_endpoint` field will be omitted from the resulting object.\n  - `impersonate_service_account` (`string`): Set the `impersonate_service_account` field on the resulting provider block. When `null`, the `impersonate_service_account` field will be omitted from the resulting object.\n  - `impersonate_service_account_delegates` (`list`): Set the `impersonate_service_account_delegates` field on the resulting provider block. When `null`, the `impersonate_service_account_delegates` field will be omitted from the resulting object.\n  - `integration_connectors_custom_endpoint` (`string`): Set the `integration_connectors_custom_endpoint` field on the resulting provider block. When `null`, the `integration_connectors_custom_endpoint` field will be omitted from the resulting object.\n  - `kms_custom_endpoint` (`string`): Set the `kms_custom_endpoint` field on the resulting provider block. When `null`, the `kms_custom_endpoint` field will be omitted from the resulting object.\n  - `logging_custom_endpoint` (`string`): Set the `logging_custom_endpoint` field on the resulting provider block. When `null`, the `logging_custom_endpoint` field will be omitted from the resulting object.\n  - `looker_custom_endpoint` (`string`): Set the `looker_custom_endpoint` field on the resulting provider block. When `null`, the `looker_custom_endpoint` field will be omitted from the resulting object.\n  - `memcache_custom_endpoint` (`string`): Set the `memcache_custom_endpoint` field on the resulting provider block. When `null`, the `memcache_custom_endpoint` field will be omitted from the resulting object.\n  - `migration_center_custom_endpoint` (`string`): Set the `migration_center_custom_endpoint` field on the resulting provider block. When `null`, the `migration_center_custom_endpoint` field will be omitted from the resulting object.\n  - `ml_engine_custom_endpoint` (`string`): Set the `ml_engine_custom_endpoint` field on the resulting provider block. When `null`, the `ml_engine_custom_endpoint` field will be omitted from the resulting object.\n  - `monitoring_custom_endpoint` (`string`): Set the `monitoring_custom_endpoint` field on the resulting provider block. When `null`, the `monitoring_custom_endpoint` field will be omitted from the resulting object.\n  - `netapp_custom_endpoint` (`string`): Set the `netapp_custom_endpoint` field on the resulting provider block. When `null`, the `netapp_custom_endpoint` field will be omitted from the resulting object.\n  - `network_connectivity_custom_endpoint` (`string`): Set the `network_connectivity_custom_endpoint` field on the resulting provider block. When `null`, the `network_connectivity_custom_endpoint` field will be omitted from the resulting object.\n  - `network_management_custom_endpoint` (`string`): Set the `network_management_custom_endpoint` field on the resulting provider block. When `null`, the `network_management_custom_endpoint` field will be omitted from the resulting object.\n  - `network_security_custom_endpoint` (`string`): Set the `network_security_custom_endpoint` field on the resulting provider block. When `null`, the `network_security_custom_endpoint` field will be omitted from the resulting object.\n  - `network_services_custom_endpoint` (`string`): Set the `network_services_custom_endpoint` field on the resulting provider block. When `null`, the `network_services_custom_endpoint` field will be omitted from the resulting object.\n  - `notebooks_custom_endpoint` (`string`): Set the `notebooks_custom_endpoint` field on the resulting provider block. When `null`, the `notebooks_custom_endpoint` field will be omitted from the resulting object.\n  - `org_policy_custom_endpoint` (`string`): Set the `org_policy_custom_endpoint` field on the resulting provider block. When `null`, the `org_policy_custom_endpoint` field will be omitted from the resulting object.\n  - `os_config_custom_endpoint` (`string`): Set the `os_config_custom_endpoint` field on the resulting provider block. When `null`, the `os_config_custom_endpoint` field will be omitted from the resulting object.\n  - `os_login_custom_endpoint` (`string`): Set the `os_login_custom_endpoint` field on the resulting provider block. When `null`, the `os_login_custom_endpoint` field will be omitted from the resulting object.\n  - `privateca_custom_endpoint` (`string`): Set the `privateca_custom_endpoint` field on the resulting provider block. When `null`, the `privateca_custom_endpoint` field will be omitted from the resulting object.\n  - `project` (`string`): Set the `project` field on the resulting provider block. When `null`, the `project` field will be omitted from the resulting object.\n  - `public_ca_custom_endpoint` (`string`): Set the `public_ca_custom_endpoint` field on the resulting provider block. When `null`, the `public_ca_custom_endpoint` field will be omitted from the resulting object.\n  - `pubsub_custom_endpoint` (`string`): Set the `pubsub_custom_endpoint` field on the resulting provider block. When `null`, the `pubsub_custom_endpoint` field will be omitted from the resulting object.\n  - `pubsub_lite_custom_endpoint` (`string`): Set the `pubsub_lite_custom_endpoint` field on the resulting provider block. When `null`, the `pubsub_lite_custom_endpoint` field will be omitted from the resulting object.\n  - `recaptcha_enterprise_custom_endpoint` (`string`): Set the `recaptcha_enterprise_custom_endpoint` field on the resulting provider block. When `null`, the `recaptcha_enterprise_custom_endpoint` field will be omitted from the resulting object.\n  - `redis_custom_endpoint` (`string`): Set the `redis_custom_endpoint` field on the resulting provider block. When `null`, the `redis_custom_endpoint` field will be omitted from the resulting object.\n  - `region` (`string`): Set the `region` field on the resulting provider block. When `null`, the `region` field will be omitted from the resulting object.\n  - `request_reason` (`string`): Set the `request_reason` field on the resulting provider block. When `null`, the `request_reason` field will be omitted from the resulting object.\n  - `request_timeout` (`string`): Set the `request_timeout` field on the resulting provider block. When `null`, the `request_timeout` field will be omitted from the resulting object.\n  - `resource_manager_custom_endpoint` (`string`): Set the `resource_manager_custom_endpoint` field on the resulting provider block. When `null`, the `resource_manager_custom_endpoint` field will be omitted from the resulting object.\n  - `resource_manager_v3_custom_endpoint` (`string`): Set the `resource_manager_v3_custom_endpoint` field on the resulting provider block. When `null`, the `resource_manager_v3_custom_endpoint` field will be omitted from the resulting object.\n  - `scopes` (`list`): Set the `scopes` field on the resulting provider block. When `null`, the `scopes` field will be omitted from the resulting object.\n  - `secret_manager_custom_endpoint` (`string`): Set the `secret_manager_custom_endpoint` field on the resulting provider block. When `null`, the `secret_manager_custom_endpoint` field will be omitted from the resulting object.\n  - `security_center_custom_endpoint` (`string`): Set the `security_center_custom_endpoint` field on the resulting provider block. When `null`, the `security_center_custom_endpoint` field will be omitted from the resulting object.\n  - `service_management_custom_endpoint` (`string`): Set the `service_management_custom_endpoint` field on the resulting provider block. When `null`, the `service_management_custom_endpoint` field will be omitted from the resulting object.\n  - `service_networking_custom_endpoint` (`string`): Set the `service_networking_custom_endpoint` field on the resulting provider block. When `null`, the `service_networking_custom_endpoint` field will be omitted from the resulting object.\n  - `service_usage_custom_endpoint` (`string`): Set the `service_usage_custom_endpoint` field on the resulting provider block. When `null`, the `service_usage_custom_endpoint` field will be omitted from the resulting object.\n  - `source_repo_custom_endpoint` (`string`): Set the `source_repo_custom_endpoint` field on the resulting provider block. When `null`, the `source_repo_custom_endpoint` field will be omitted from the resulting object.\n  - `spanner_custom_endpoint` (`string`): Set the `spanner_custom_endpoint` field on the resulting provider block. When `null`, the `spanner_custom_endpoint` field will be omitted from the resulting object.\n  - `sql_custom_endpoint` (`string`): Set the `sql_custom_endpoint` field on the resulting provider block. When `null`, the `sql_custom_endpoint` field will be omitted from the resulting object.\n  - `storage_custom_endpoint` (`string`): Set the `storage_custom_endpoint` field on the resulting provider block. When `null`, the `storage_custom_endpoint` field will be omitted from the resulting object.\n  - `storage_insights_custom_endpoint` (`string`): Set the `storage_insights_custom_endpoint` field on the resulting provider block. When `null`, the `storage_insights_custom_endpoint` field will be omitted from the resulting object.\n  - `storage_transfer_custom_endpoint` (`string`): Set the `storage_transfer_custom_endpoint` field on the resulting provider block. When `null`, the `storage_transfer_custom_endpoint` field will be omitted from the resulting object.\n  - `tags_custom_endpoint` (`string`): Set the `tags_custom_endpoint` field on the resulting provider block. When `null`, the `tags_custom_endpoint` field will be omitted from the resulting object.\n  - `tags_location_custom_endpoint` (`string`): Set the `tags_location_custom_endpoint` field on the resulting provider block. When `null`, the `tags_location_custom_endpoint` field will be omitted from the resulting object.\n  - `tpu_custom_endpoint` (`string`): Set the `tpu_custom_endpoint` field on the resulting provider block. When `null`, the `tpu_custom_endpoint` field will be omitted from the resulting object.\n  - `universe_domain` (`string`): Set the `universe_domain` field on the resulting provider block. When `null`, the `universe_domain` field will be omitted from the resulting object.\n  - `user_project_override` (`bool`): Set the `user_project_override` field on the resulting provider block. When `null`, the `user_project_override` field will be omitted from the resulting object.\n  - `vertex_ai_custom_endpoint` (`string`): Set the `vertex_ai_custom_endpoint` field on the resulting provider block. When `null`, the `vertex_ai_custom_endpoint` field will be omitted from the resulting object.\n  - `vmwareengine_custom_endpoint` (`string`): Set the `vmwareengine_custom_endpoint` field on the resulting provider block. When `null`, the `vmwareengine_custom_endpoint` field will be omitted from the resulting object.\n  - `vpc_access_custom_endpoint` (`string`): Set the `vpc_access_custom_endpoint` field on the resulting provider block. When `null`, the `vpc_access_custom_endpoint` field will be omitted from the resulting object.\n  - `workflows_custom_endpoint` (`string`): Set the `workflows_custom_endpoint` field on the resulting provider block. When `null`, the `workflows_custom_endpoint` field will be omitted from the resulting object.\n  - `zone` (`string`): Set the `zone` field on the resulting provider block. When `null`, the `zone` field will be omitted from the resulting object.\n  - `batching` (`list[obj]`): Set the `batching` field on the resulting provider block. When `null`, the `batching` sub block will be omitted from the resulting object. When setting the sub block, it is recommended to construct the object using the [google.provider.batching.new](#fn-googlebatchingnew) constructor.\n  - `alias` (`string`): The provider `alias` to set for this instance of the provider block. When `null`, the `alias`\n  field will be omitted from the resulting provider block.\n  - `src` (`string`): The provider `source` to set on the resulting `required_providers` block. If `src` or `version` is\n  set and is not `null`, a `required_providers` block and entry for the provider will be injected into the document.\n  - `version` (`string`): The provider `version` to set on the resulting `required_providers` block. If `src` or\n  `version` is set and is not `null`, a `required_providers` block and entry for the provider will be injected into the\n  document.\n\n\n**Returns**:\n- A mixin object that injects the new provider (and optionally, `required_providers` block) into the root Terraform configuration.\n', args=[]),
  new(
    access_approval_custom_endpoint=null,
    access_context_manager_custom_endpoint=null,
    access_token=null,
    active_directory_custom_endpoint=null,
    alloydb_custom_endpoint=null,
    apigee_custom_endpoint=null,
    apikeys_custom_endpoint=null,
    app_engine_custom_endpoint=null,
    artifact_registry_custom_endpoint=null,
    assured_workloads_custom_endpoint=null,
    batching=null,
    beyondcorp_custom_endpoint=null,
    big_query_custom_endpoint=null,
    biglake_custom_endpoint=null,
    bigquery_analytics_hub_custom_endpoint=null,
    bigquery_connection_custom_endpoint=null,
    bigquery_data_transfer_custom_endpoint=null,
    bigquery_datapolicy_custom_endpoint=null,
    bigquery_reservation_custom_endpoint=null,
    bigtable_custom_endpoint=null,
    billing_custom_endpoint=null,
    billing_project=null,
    binary_authorization_custom_endpoint=null,
    certificate_manager_custom_endpoint=null,
    cloud_asset_custom_endpoint=null,
    cloud_billing_custom_endpoint=null,
    cloud_build_custom_endpoint=null,
    cloud_build_worker_pool_custom_endpoint=null,
    cloud_functions_custom_endpoint=null,
    cloud_identity_custom_endpoint=null,
    cloud_ids_custom_endpoint=null,
    cloud_resource_manager_custom_endpoint=null,
    cloud_run_custom_endpoint=null,
    cloud_run_v2_custom_endpoint=null,
    cloud_scheduler_custom_endpoint=null,
    cloud_tasks_custom_endpoint=null,
    cloudbuildv2_custom_endpoint=null,
    clouddeploy_custom_endpoint=null,
    cloudfunctions2_custom_endpoint=null,
    composer_custom_endpoint=null,
    compute_custom_endpoint=null,
    container_analysis_custom_endpoint=null,
    container_attached_custom_endpoint=null,
    container_aws_custom_endpoint=null,
    container_azure_custom_endpoint=null,
    container_custom_endpoint=null,
    core_billing_custom_endpoint=null,
    credentials=null,
    data_catalog_custom_endpoint=null,
    data_fusion_custom_endpoint=null,
    data_loss_prevention_custom_endpoint=null,
    data_pipeline_custom_endpoint=null,
    database_migration_service_custom_endpoint=null,
    dataflow_custom_endpoint=null,
    dataplex_custom_endpoint=null,
    dataproc_custom_endpoint=null,
    dataproc_metastore_custom_endpoint=null,
    datastore_custom_endpoint=null,
    datastream_custom_endpoint=null,
    default_labels=null,
    deployment_manager_custom_endpoint=null,
    dialogflow_custom_endpoint=null,
    dialogflow_cx_custom_endpoint=null,
    dns_custom_endpoint=null,
    document_ai_custom_endpoint=null,
    document_ai_warehouse_custom_endpoint=null,
    edgecontainer_custom_endpoint=null,
    edgenetwork_custom_endpoint=null,
    essential_contacts_custom_endpoint=null,
    eventarc_custom_endpoint=null,
    filestore_custom_endpoint=null,
    firebaserules_custom_endpoint=null,
    firestore_custom_endpoint=null,
    gke_backup_custom_endpoint=null,
    gke_hub2_custom_endpoint=null,
    gke_hub_custom_endpoint=null,
    gkehub_feature_custom_endpoint=null,
    gkeonprem_custom_endpoint=null,
    healthcare_custom_endpoint=null,
    iam2_custom_endpoint=null,
    iam_beta_custom_endpoint=null,
    iam_credentials_custom_endpoint=null,
    iam_custom_endpoint=null,
    iam_workforce_pool_custom_endpoint=null,
    iap_custom_endpoint=null,
    identity_platform_custom_endpoint=null,
    impersonate_service_account=null,
    impersonate_service_account_delegates=null,
    integration_connectors_custom_endpoint=null,
    kms_custom_endpoint=null,
    logging_custom_endpoint=null,
    looker_custom_endpoint=null,
    memcache_custom_endpoint=null,
    migration_center_custom_endpoint=null,
    ml_engine_custom_endpoint=null,
    monitoring_custom_endpoint=null,
    netapp_custom_endpoint=null,
    network_connectivity_custom_endpoint=null,
    network_management_custom_endpoint=null,
    network_security_custom_endpoint=null,
    network_services_custom_endpoint=null,
    notebooks_custom_endpoint=null,
    org_policy_custom_endpoint=null,
    os_config_custom_endpoint=null,
    os_login_custom_endpoint=null,
    privateca_custom_endpoint=null,
    project=null,
    public_ca_custom_endpoint=null,
    pubsub_custom_endpoint=null,
    pubsub_lite_custom_endpoint=null,
    recaptcha_enterprise_custom_endpoint=null,
    redis_custom_endpoint=null,
    region=null,
    request_reason=null,
    request_timeout=null,
    resource_manager_custom_endpoint=null,
    resource_manager_v3_custom_endpoint=null,
    scopes=null,
    secret_manager_custom_endpoint=null,
    security_center_custom_endpoint=null,
    service_management_custom_endpoint=null,
    service_networking_custom_endpoint=null,
    service_usage_custom_endpoint=null,
    source_repo_custom_endpoint=null,
    spanner_custom_endpoint=null,
    sql_custom_endpoint=null,
    storage_custom_endpoint=null,
    storage_insights_custom_endpoint=null,
    storage_transfer_custom_endpoint=null,
    tags_custom_endpoint=null,
    tags_location_custom_endpoint=null,
    tpu_custom_endpoint=null,
    universe_domain=null,
    user_project_override=null,
    vertex_ai_custom_endpoint=null,
    vmwareengine_custom_endpoint=null,
    vpc_access_custom_endpoint=null,
    workflows_custom_endpoint=null,
    zone=null,
    alias=null,
    src=null,
    version=null
  ):: tf.withProvider(
    name='google',
    alias=alias,
    src=src,
    version=version,
    attrs=self.newAttrs(
      access_approval_custom_endpoint=access_approval_custom_endpoint,
      access_context_manager_custom_endpoint=access_context_manager_custom_endpoint,
      access_token=access_token,
      active_directory_custom_endpoint=active_directory_custom_endpoint,
      alloydb_custom_endpoint=alloydb_custom_endpoint,
      apigee_custom_endpoint=apigee_custom_endpoint,
      apikeys_custom_endpoint=apikeys_custom_endpoint,
      app_engine_custom_endpoint=app_engine_custom_endpoint,
      artifact_registry_custom_endpoint=artifact_registry_custom_endpoint,
      assured_workloads_custom_endpoint=assured_workloads_custom_endpoint,
      batching=batching,
      beyondcorp_custom_endpoint=beyondcorp_custom_endpoint,
      big_query_custom_endpoint=big_query_custom_endpoint,
      biglake_custom_endpoint=biglake_custom_endpoint,
      bigquery_analytics_hub_custom_endpoint=bigquery_analytics_hub_custom_endpoint,
      bigquery_connection_custom_endpoint=bigquery_connection_custom_endpoint,
      bigquery_data_transfer_custom_endpoint=bigquery_data_transfer_custom_endpoint,
      bigquery_datapolicy_custom_endpoint=bigquery_datapolicy_custom_endpoint,
      bigquery_reservation_custom_endpoint=bigquery_reservation_custom_endpoint,
      bigtable_custom_endpoint=bigtable_custom_endpoint,
      billing_custom_endpoint=billing_custom_endpoint,
      billing_project=billing_project,
      binary_authorization_custom_endpoint=binary_authorization_custom_endpoint,
      certificate_manager_custom_endpoint=certificate_manager_custom_endpoint,
      cloud_asset_custom_endpoint=cloud_asset_custom_endpoint,
      cloud_billing_custom_endpoint=cloud_billing_custom_endpoint,
      cloud_build_custom_endpoint=cloud_build_custom_endpoint,
      cloud_build_worker_pool_custom_endpoint=cloud_build_worker_pool_custom_endpoint,
      cloud_functions_custom_endpoint=cloud_functions_custom_endpoint,
      cloud_identity_custom_endpoint=cloud_identity_custom_endpoint,
      cloud_ids_custom_endpoint=cloud_ids_custom_endpoint,
      cloud_resource_manager_custom_endpoint=cloud_resource_manager_custom_endpoint,
      cloud_run_custom_endpoint=cloud_run_custom_endpoint,
      cloud_run_v2_custom_endpoint=cloud_run_v2_custom_endpoint,
      cloud_scheduler_custom_endpoint=cloud_scheduler_custom_endpoint,
      cloud_tasks_custom_endpoint=cloud_tasks_custom_endpoint,
      cloudbuildv2_custom_endpoint=cloudbuildv2_custom_endpoint,
      clouddeploy_custom_endpoint=clouddeploy_custom_endpoint,
      cloudfunctions2_custom_endpoint=cloudfunctions2_custom_endpoint,
      composer_custom_endpoint=composer_custom_endpoint,
      compute_custom_endpoint=compute_custom_endpoint,
      container_analysis_custom_endpoint=container_analysis_custom_endpoint,
      container_attached_custom_endpoint=container_attached_custom_endpoint,
      container_aws_custom_endpoint=container_aws_custom_endpoint,
      container_azure_custom_endpoint=container_azure_custom_endpoint,
      container_custom_endpoint=container_custom_endpoint,
      core_billing_custom_endpoint=core_billing_custom_endpoint,
      credentials=credentials,
      data_catalog_custom_endpoint=data_catalog_custom_endpoint,
      data_fusion_custom_endpoint=data_fusion_custom_endpoint,
      data_loss_prevention_custom_endpoint=data_loss_prevention_custom_endpoint,
      data_pipeline_custom_endpoint=data_pipeline_custom_endpoint,
      database_migration_service_custom_endpoint=database_migration_service_custom_endpoint,
      dataflow_custom_endpoint=dataflow_custom_endpoint,
      dataplex_custom_endpoint=dataplex_custom_endpoint,
      dataproc_custom_endpoint=dataproc_custom_endpoint,
      dataproc_metastore_custom_endpoint=dataproc_metastore_custom_endpoint,
      datastore_custom_endpoint=datastore_custom_endpoint,
      datastream_custom_endpoint=datastream_custom_endpoint,
      default_labels=default_labels,
      deployment_manager_custom_endpoint=deployment_manager_custom_endpoint,
      dialogflow_custom_endpoint=dialogflow_custom_endpoint,
      dialogflow_cx_custom_endpoint=dialogflow_cx_custom_endpoint,
      dns_custom_endpoint=dns_custom_endpoint,
      document_ai_custom_endpoint=document_ai_custom_endpoint,
      document_ai_warehouse_custom_endpoint=document_ai_warehouse_custom_endpoint,
      edgecontainer_custom_endpoint=edgecontainer_custom_endpoint,
      edgenetwork_custom_endpoint=edgenetwork_custom_endpoint,
      essential_contacts_custom_endpoint=essential_contacts_custom_endpoint,
      eventarc_custom_endpoint=eventarc_custom_endpoint,
      filestore_custom_endpoint=filestore_custom_endpoint,
      firebaserules_custom_endpoint=firebaserules_custom_endpoint,
      firestore_custom_endpoint=firestore_custom_endpoint,
      gke_backup_custom_endpoint=gke_backup_custom_endpoint,
      gke_hub2_custom_endpoint=gke_hub2_custom_endpoint,
      gke_hub_custom_endpoint=gke_hub_custom_endpoint,
      gkehub_feature_custom_endpoint=gkehub_feature_custom_endpoint,
      gkeonprem_custom_endpoint=gkeonprem_custom_endpoint,
      healthcare_custom_endpoint=healthcare_custom_endpoint,
      iam2_custom_endpoint=iam2_custom_endpoint,
      iam_beta_custom_endpoint=iam_beta_custom_endpoint,
      iam_credentials_custom_endpoint=iam_credentials_custom_endpoint,
      iam_custom_endpoint=iam_custom_endpoint,
      iam_workforce_pool_custom_endpoint=iam_workforce_pool_custom_endpoint,
      iap_custom_endpoint=iap_custom_endpoint,
      identity_platform_custom_endpoint=identity_platform_custom_endpoint,
      impersonate_service_account=impersonate_service_account,
      impersonate_service_account_delegates=impersonate_service_account_delegates,
      integration_connectors_custom_endpoint=integration_connectors_custom_endpoint,
      kms_custom_endpoint=kms_custom_endpoint,
      logging_custom_endpoint=logging_custom_endpoint,
      looker_custom_endpoint=looker_custom_endpoint,
      memcache_custom_endpoint=memcache_custom_endpoint,
      migration_center_custom_endpoint=migration_center_custom_endpoint,
      ml_engine_custom_endpoint=ml_engine_custom_endpoint,
      monitoring_custom_endpoint=monitoring_custom_endpoint,
      netapp_custom_endpoint=netapp_custom_endpoint,
      network_connectivity_custom_endpoint=network_connectivity_custom_endpoint,
      network_management_custom_endpoint=network_management_custom_endpoint,
      network_security_custom_endpoint=network_security_custom_endpoint,
      network_services_custom_endpoint=network_services_custom_endpoint,
      notebooks_custom_endpoint=notebooks_custom_endpoint,
      org_policy_custom_endpoint=org_policy_custom_endpoint,
      os_config_custom_endpoint=os_config_custom_endpoint,
      os_login_custom_endpoint=os_login_custom_endpoint,
      privateca_custom_endpoint=privateca_custom_endpoint,
      project=project,
      public_ca_custom_endpoint=public_ca_custom_endpoint,
      pubsub_custom_endpoint=pubsub_custom_endpoint,
      pubsub_lite_custom_endpoint=pubsub_lite_custom_endpoint,
      recaptcha_enterprise_custom_endpoint=recaptcha_enterprise_custom_endpoint,
      redis_custom_endpoint=redis_custom_endpoint,
      region=region,
      request_reason=request_reason,
      request_timeout=request_timeout,
      resource_manager_custom_endpoint=resource_manager_custom_endpoint,
      resource_manager_v3_custom_endpoint=resource_manager_v3_custom_endpoint,
      scopes=scopes,
      secret_manager_custom_endpoint=secret_manager_custom_endpoint,
      security_center_custom_endpoint=security_center_custom_endpoint,
      service_management_custom_endpoint=service_management_custom_endpoint,
      service_networking_custom_endpoint=service_networking_custom_endpoint,
      service_usage_custom_endpoint=service_usage_custom_endpoint,
      source_repo_custom_endpoint=source_repo_custom_endpoint,
      spanner_custom_endpoint=spanner_custom_endpoint,
      sql_custom_endpoint=sql_custom_endpoint,
      storage_custom_endpoint=storage_custom_endpoint,
      storage_insights_custom_endpoint=storage_insights_custom_endpoint,
      storage_transfer_custom_endpoint=storage_transfer_custom_endpoint,
      tags_custom_endpoint=tags_custom_endpoint,
      tags_location_custom_endpoint=tags_location_custom_endpoint,
      tpu_custom_endpoint=tpu_custom_endpoint,
      universe_domain=universe_domain,
      user_project_override=user_project_override,
      vertex_ai_custom_endpoint=vertex_ai_custom_endpoint,
      vmwareengine_custom_endpoint=vmwareengine_custom_endpoint,
      vpc_access_custom_endpoint=vpc_access_custom_endpoint,
      workflows_custom_endpoint=workflows_custom_endpoint,
      zone=zone
    )
  ),
  '#newAttrs':: d.fn(help='\n`google.provider.` constructs a new object with attributes and blocks configured for the `google`\nTerraform `provider`.\n\nUnlike [google.provider.new](#fn-googlenew), this function will not inject the `provider`\nblock into the root Terraform document. Instead, this must be passed in as the `attrs` argument for the\n[tf.withProvider](https://github.com/tf-libsonnet/core/tree/main/docs#fn-withprovider) function to build a complete block.\n\nThis is most useful when you need to preprocess the attributes with functions, conditional, or looping logic prior to\ninjecting into a complete block.\n\n**Args**:\n  - `access_approval_custom_endpoint` (`string`): Set the `access_approval_custom_endpoint` field on the resulting object. When `null`, the `access_approval_custom_endpoint` field will be omitted from the resulting object.\n  - `access_context_manager_custom_endpoint` (`string`): Set the `access_context_manager_custom_endpoint` field on the resulting object. When `null`, the `access_context_manager_custom_endpoint` field will be omitted from the resulting object.\n  - `access_token` (`string`): Set the `access_token` field on the resulting object. When `null`, the `access_token` field will be omitted from the resulting object.\n  - `active_directory_custom_endpoint` (`string`): Set the `active_directory_custom_endpoint` field on the resulting object. When `null`, the `active_directory_custom_endpoint` field will be omitted from the resulting object.\n  - `alloydb_custom_endpoint` (`string`): Set the `alloydb_custom_endpoint` field on the resulting object. When `null`, the `alloydb_custom_endpoint` field will be omitted from the resulting object.\n  - `apigee_custom_endpoint` (`string`): Set the `apigee_custom_endpoint` field on the resulting object. When `null`, the `apigee_custom_endpoint` field will be omitted from the resulting object.\n  - `apikeys_custom_endpoint` (`string`): Set the `apikeys_custom_endpoint` field on the resulting object. When `null`, the `apikeys_custom_endpoint` field will be omitted from the resulting object.\n  - `app_engine_custom_endpoint` (`string`): Set the `app_engine_custom_endpoint` field on the resulting object. When `null`, the `app_engine_custom_endpoint` field will be omitted from the resulting object.\n  - `artifact_registry_custom_endpoint` (`string`): Set the `artifact_registry_custom_endpoint` field on the resulting object. When `null`, the `artifact_registry_custom_endpoint` field will be omitted from the resulting object.\n  - `assured_workloads_custom_endpoint` (`string`): Set the `assured_workloads_custom_endpoint` field on the resulting object. When `null`, the `assured_workloads_custom_endpoint` field will be omitted from the resulting object.\n  - `beyondcorp_custom_endpoint` (`string`): Set the `beyondcorp_custom_endpoint` field on the resulting object. When `null`, the `beyondcorp_custom_endpoint` field will be omitted from the resulting object.\n  - `big_query_custom_endpoint` (`string`): Set the `big_query_custom_endpoint` field on the resulting object. When `null`, the `big_query_custom_endpoint` field will be omitted from the resulting object.\n  - `biglake_custom_endpoint` (`string`): Set the `biglake_custom_endpoint` field on the resulting object. When `null`, the `biglake_custom_endpoint` field will be omitted from the resulting object.\n  - `bigquery_analytics_hub_custom_endpoint` (`string`): Set the `bigquery_analytics_hub_custom_endpoint` field on the resulting object. When `null`, the `bigquery_analytics_hub_custom_endpoint` field will be omitted from the resulting object.\n  - `bigquery_connection_custom_endpoint` (`string`): Set the `bigquery_connection_custom_endpoint` field on the resulting object. When `null`, the `bigquery_connection_custom_endpoint` field will be omitted from the resulting object.\n  - `bigquery_data_transfer_custom_endpoint` (`string`): Set the `bigquery_data_transfer_custom_endpoint` field on the resulting object. When `null`, the `bigquery_data_transfer_custom_endpoint` field will be omitted from the resulting object.\n  - `bigquery_datapolicy_custom_endpoint` (`string`): Set the `bigquery_datapolicy_custom_endpoint` field on the resulting object. When `null`, the `bigquery_datapolicy_custom_endpoint` field will be omitted from the resulting object.\n  - `bigquery_reservation_custom_endpoint` (`string`): Set the `bigquery_reservation_custom_endpoint` field on the resulting object. When `null`, the `bigquery_reservation_custom_endpoint` field will be omitted from the resulting object.\n  - `bigtable_custom_endpoint` (`string`): Set the `bigtable_custom_endpoint` field on the resulting object. When `null`, the `bigtable_custom_endpoint` field will be omitted from the resulting object.\n  - `billing_custom_endpoint` (`string`): Set the `billing_custom_endpoint` field on the resulting object. When `null`, the `billing_custom_endpoint` field will be omitted from the resulting object.\n  - `billing_project` (`string`): Set the `billing_project` field on the resulting object. When `null`, the `billing_project` field will be omitted from the resulting object.\n  - `binary_authorization_custom_endpoint` (`string`): Set the `binary_authorization_custom_endpoint` field on the resulting object. When `null`, the `binary_authorization_custom_endpoint` field will be omitted from the resulting object.\n  - `certificate_manager_custom_endpoint` (`string`): Set the `certificate_manager_custom_endpoint` field on the resulting object. When `null`, the `certificate_manager_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_asset_custom_endpoint` (`string`): Set the `cloud_asset_custom_endpoint` field on the resulting object. When `null`, the `cloud_asset_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_billing_custom_endpoint` (`string`): Set the `cloud_billing_custom_endpoint` field on the resulting object. When `null`, the `cloud_billing_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_build_custom_endpoint` (`string`): Set the `cloud_build_custom_endpoint` field on the resulting object. When `null`, the `cloud_build_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_build_worker_pool_custom_endpoint` (`string`): Set the `cloud_build_worker_pool_custom_endpoint` field on the resulting object. When `null`, the `cloud_build_worker_pool_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_functions_custom_endpoint` (`string`): Set the `cloud_functions_custom_endpoint` field on the resulting object. When `null`, the `cloud_functions_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_identity_custom_endpoint` (`string`): Set the `cloud_identity_custom_endpoint` field on the resulting object. When `null`, the `cloud_identity_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_ids_custom_endpoint` (`string`): Set the `cloud_ids_custom_endpoint` field on the resulting object. When `null`, the `cloud_ids_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_resource_manager_custom_endpoint` (`string`): Set the `cloud_resource_manager_custom_endpoint` field on the resulting object. When `null`, the `cloud_resource_manager_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_run_custom_endpoint` (`string`): Set the `cloud_run_custom_endpoint` field on the resulting object. When `null`, the `cloud_run_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_run_v2_custom_endpoint` (`string`): Set the `cloud_run_v2_custom_endpoint` field on the resulting object. When `null`, the `cloud_run_v2_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_scheduler_custom_endpoint` (`string`): Set the `cloud_scheduler_custom_endpoint` field on the resulting object. When `null`, the `cloud_scheduler_custom_endpoint` field will be omitted from the resulting object.\n  - `cloud_tasks_custom_endpoint` (`string`): Set the `cloud_tasks_custom_endpoint` field on the resulting object. When `null`, the `cloud_tasks_custom_endpoint` field will be omitted from the resulting object.\n  - `cloudbuildv2_custom_endpoint` (`string`): Set the `cloudbuildv2_custom_endpoint` field on the resulting object. When `null`, the `cloudbuildv2_custom_endpoint` field will be omitted from the resulting object.\n  - `clouddeploy_custom_endpoint` (`string`): Set the `clouddeploy_custom_endpoint` field on the resulting object. When `null`, the `clouddeploy_custom_endpoint` field will be omitted from the resulting object.\n  - `cloudfunctions2_custom_endpoint` (`string`): Set the `cloudfunctions2_custom_endpoint` field on the resulting object. When `null`, the `cloudfunctions2_custom_endpoint` field will be omitted from the resulting object.\n  - `composer_custom_endpoint` (`string`): Set the `composer_custom_endpoint` field on the resulting object. When `null`, the `composer_custom_endpoint` field will be omitted from the resulting object.\n  - `compute_custom_endpoint` (`string`): Set the `compute_custom_endpoint` field on the resulting object. When `null`, the `compute_custom_endpoint` field will be omitted from the resulting object.\n  - `container_analysis_custom_endpoint` (`string`): Set the `container_analysis_custom_endpoint` field on the resulting object. When `null`, the `container_analysis_custom_endpoint` field will be omitted from the resulting object.\n  - `container_attached_custom_endpoint` (`string`): Set the `container_attached_custom_endpoint` field on the resulting object. When `null`, the `container_attached_custom_endpoint` field will be omitted from the resulting object.\n  - `container_aws_custom_endpoint` (`string`): Set the `container_aws_custom_endpoint` field on the resulting object. When `null`, the `container_aws_custom_endpoint` field will be omitted from the resulting object.\n  - `container_azure_custom_endpoint` (`string`): Set the `container_azure_custom_endpoint` field on the resulting object. When `null`, the `container_azure_custom_endpoint` field will be omitted from the resulting object.\n  - `container_custom_endpoint` (`string`): Set the `container_custom_endpoint` field on the resulting object. When `null`, the `container_custom_endpoint` field will be omitted from the resulting object.\n  - `core_billing_custom_endpoint` (`string`): Set the `core_billing_custom_endpoint` field on the resulting object. When `null`, the `core_billing_custom_endpoint` field will be omitted from the resulting object.\n  - `credentials` (`string`): Set the `credentials` field on the resulting object. When `null`, the `credentials` field will be omitted from the resulting object.\n  - `data_catalog_custom_endpoint` (`string`): Set the `data_catalog_custom_endpoint` field on the resulting object. When `null`, the `data_catalog_custom_endpoint` field will be omitted from the resulting object.\n  - `data_fusion_custom_endpoint` (`string`): Set the `data_fusion_custom_endpoint` field on the resulting object. When `null`, the `data_fusion_custom_endpoint` field will be omitted from the resulting object.\n  - `data_loss_prevention_custom_endpoint` (`string`): Set the `data_loss_prevention_custom_endpoint` field on the resulting object. When `null`, the `data_loss_prevention_custom_endpoint` field will be omitted from the resulting object.\n  - `data_pipeline_custom_endpoint` (`string`): Set the `data_pipeline_custom_endpoint` field on the resulting object. When `null`, the `data_pipeline_custom_endpoint` field will be omitted from the resulting object.\n  - `database_migration_service_custom_endpoint` (`string`): Set the `database_migration_service_custom_endpoint` field on the resulting object. When `null`, the `database_migration_service_custom_endpoint` field will be omitted from the resulting object.\n  - `dataflow_custom_endpoint` (`string`): Set the `dataflow_custom_endpoint` field on the resulting object. When `null`, the `dataflow_custom_endpoint` field will be omitted from the resulting object.\n  - `dataplex_custom_endpoint` (`string`): Set the `dataplex_custom_endpoint` field on the resulting object. When `null`, the `dataplex_custom_endpoint` field will be omitted from the resulting object.\n  - `dataproc_custom_endpoint` (`string`): Set the `dataproc_custom_endpoint` field on the resulting object. When `null`, the `dataproc_custom_endpoint` field will be omitted from the resulting object.\n  - `dataproc_metastore_custom_endpoint` (`string`): Set the `dataproc_metastore_custom_endpoint` field on the resulting object. When `null`, the `dataproc_metastore_custom_endpoint` field will be omitted from the resulting object.\n  - `datastore_custom_endpoint` (`string`): Set the `datastore_custom_endpoint` field on the resulting object. When `null`, the `datastore_custom_endpoint` field will be omitted from the resulting object.\n  - `datastream_custom_endpoint` (`string`): Set the `datastream_custom_endpoint` field on the resulting object. When `null`, the `datastream_custom_endpoint` field will be omitted from the resulting object.\n  - `default_labels` (`obj`): Set the `default_labels` field on the resulting object. When `null`, the `default_labels` field will be omitted from the resulting object.\n  - `deployment_manager_custom_endpoint` (`string`): Set the `deployment_manager_custom_endpoint` field on the resulting object. When `null`, the `deployment_manager_custom_endpoint` field will be omitted from the resulting object.\n  - `dialogflow_custom_endpoint` (`string`): Set the `dialogflow_custom_endpoint` field on the resulting object. When `null`, the `dialogflow_custom_endpoint` field will be omitted from the resulting object.\n  - `dialogflow_cx_custom_endpoint` (`string`): Set the `dialogflow_cx_custom_endpoint` field on the resulting object. When `null`, the `dialogflow_cx_custom_endpoint` field will be omitted from the resulting object.\n  - `dns_custom_endpoint` (`string`): Set the `dns_custom_endpoint` field on the resulting object. When `null`, the `dns_custom_endpoint` field will be omitted from the resulting object.\n  - `document_ai_custom_endpoint` (`string`): Set the `document_ai_custom_endpoint` field on the resulting object. When `null`, the `document_ai_custom_endpoint` field will be omitted from the resulting object.\n  - `document_ai_warehouse_custom_endpoint` (`string`): Set the `document_ai_warehouse_custom_endpoint` field on the resulting object. When `null`, the `document_ai_warehouse_custom_endpoint` field will be omitted from the resulting object.\n  - `edgecontainer_custom_endpoint` (`string`): Set the `edgecontainer_custom_endpoint` field on the resulting object. When `null`, the `edgecontainer_custom_endpoint` field will be omitted from the resulting object.\n  - `edgenetwork_custom_endpoint` (`string`): Set the `edgenetwork_custom_endpoint` field on the resulting object. When `null`, the `edgenetwork_custom_endpoint` field will be omitted from the resulting object.\n  - `essential_contacts_custom_endpoint` (`string`): Set the `essential_contacts_custom_endpoint` field on the resulting object. When `null`, the `essential_contacts_custom_endpoint` field will be omitted from the resulting object.\n  - `eventarc_custom_endpoint` (`string`): Set the `eventarc_custom_endpoint` field on the resulting object. When `null`, the `eventarc_custom_endpoint` field will be omitted from the resulting object.\n  - `filestore_custom_endpoint` (`string`): Set the `filestore_custom_endpoint` field on the resulting object. When `null`, the `filestore_custom_endpoint` field will be omitted from the resulting object.\n  - `firebaserules_custom_endpoint` (`string`): Set the `firebaserules_custom_endpoint` field on the resulting object. When `null`, the `firebaserules_custom_endpoint` field will be omitted from the resulting object.\n  - `firestore_custom_endpoint` (`string`): Set the `firestore_custom_endpoint` field on the resulting object. When `null`, the `firestore_custom_endpoint` field will be omitted from the resulting object.\n  - `gke_backup_custom_endpoint` (`string`): Set the `gke_backup_custom_endpoint` field on the resulting object. When `null`, the `gke_backup_custom_endpoint` field will be omitted from the resulting object.\n  - `gke_hub2_custom_endpoint` (`string`): Set the `gke_hub2_custom_endpoint` field on the resulting object. When `null`, the `gke_hub2_custom_endpoint` field will be omitted from the resulting object.\n  - `gke_hub_custom_endpoint` (`string`): Set the `gke_hub_custom_endpoint` field on the resulting object. When `null`, the `gke_hub_custom_endpoint` field will be omitted from the resulting object.\n  - `gkehub_feature_custom_endpoint` (`string`): Set the `gkehub_feature_custom_endpoint` field on the resulting object. When `null`, the `gkehub_feature_custom_endpoint` field will be omitted from the resulting object.\n  - `gkeonprem_custom_endpoint` (`string`): Set the `gkeonprem_custom_endpoint` field on the resulting object. When `null`, the `gkeonprem_custom_endpoint` field will be omitted from the resulting object.\n  - `healthcare_custom_endpoint` (`string`): Set the `healthcare_custom_endpoint` field on the resulting object. When `null`, the `healthcare_custom_endpoint` field will be omitted from the resulting object.\n  - `iam2_custom_endpoint` (`string`): Set the `iam2_custom_endpoint` field on the resulting object. When `null`, the `iam2_custom_endpoint` field will be omitted from the resulting object.\n  - `iam_beta_custom_endpoint` (`string`): Set the `iam_beta_custom_endpoint` field on the resulting object. When `null`, the `iam_beta_custom_endpoint` field will be omitted from the resulting object.\n  - `iam_credentials_custom_endpoint` (`string`): Set the `iam_credentials_custom_endpoint` field on the resulting object. When `null`, the `iam_credentials_custom_endpoint` field will be omitted from the resulting object.\n  - `iam_custom_endpoint` (`string`): Set the `iam_custom_endpoint` field on the resulting object. When `null`, the `iam_custom_endpoint` field will be omitted from the resulting object.\n  - `iam_workforce_pool_custom_endpoint` (`string`): Set the `iam_workforce_pool_custom_endpoint` field on the resulting object. When `null`, the `iam_workforce_pool_custom_endpoint` field will be omitted from the resulting object.\n  - `iap_custom_endpoint` (`string`): Set the `iap_custom_endpoint` field on the resulting object. When `null`, the `iap_custom_endpoint` field will be omitted from the resulting object.\n  - `identity_platform_custom_endpoint` (`string`): Set the `identity_platform_custom_endpoint` field on the resulting object. When `null`, the `identity_platform_custom_endpoint` field will be omitted from the resulting object.\n  - `impersonate_service_account` (`string`): Set the `impersonate_service_account` field on the resulting object. When `null`, the `impersonate_service_account` field will be omitted from the resulting object.\n  - `impersonate_service_account_delegates` (`list`): Set the `impersonate_service_account_delegates` field on the resulting object. When `null`, the `impersonate_service_account_delegates` field will be omitted from the resulting object.\n  - `integration_connectors_custom_endpoint` (`string`): Set the `integration_connectors_custom_endpoint` field on the resulting object. When `null`, the `integration_connectors_custom_endpoint` field will be omitted from the resulting object.\n  - `kms_custom_endpoint` (`string`): Set the `kms_custom_endpoint` field on the resulting object. When `null`, the `kms_custom_endpoint` field will be omitted from the resulting object.\n  - `logging_custom_endpoint` (`string`): Set the `logging_custom_endpoint` field on the resulting object. When `null`, the `logging_custom_endpoint` field will be omitted from the resulting object.\n  - `looker_custom_endpoint` (`string`): Set the `looker_custom_endpoint` field on the resulting object. When `null`, the `looker_custom_endpoint` field will be omitted from the resulting object.\n  - `memcache_custom_endpoint` (`string`): Set the `memcache_custom_endpoint` field on the resulting object. When `null`, the `memcache_custom_endpoint` field will be omitted from the resulting object.\n  - `migration_center_custom_endpoint` (`string`): Set the `migration_center_custom_endpoint` field on the resulting object. When `null`, the `migration_center_custom_endpoint` field will be omitted from the resulting object.\n  - `ml_engine_custom_endpoint` (`string`): Set the `ml_engine_custom_endpoint` field on the resulting object. When `null`, the `ml_engine_custom_endpoint` field will be omitted from the resulting object.\n  - `monitoring_custom_endpoint` (`string`): Set the `monitoring_custom_endpoint` field on the resulting object. When `null`, the `monitoring_custom_endpoint` field will be omitted from the resulting object.\n  - `netapp_custom_endpoint` (`string`): Set the `netapp_custom_endpoint` field on the resulting object. When `null`, the `netapp_custom_endpoint` field will be omitted from the resulting object.\n  - `network_connectivity_custom_endpoint` (`string`): Set the `network_connectivity_custom_endpoint` field on the resulting object. When `null`, the `network_connectivity_custom_endpoint` field will be omitted from the resulting object.\n  - `network_management_custom_endpoint` (`string`): Set the `network_management_custom_endpoint` field on the resulting object. When `null`, the `network_management_custom_endpoint` field will be omitted from the resulting object.\n  - `network_security_custom_endpoint` (`string`): Set the `network_security_custom_endpoint` field on the resulting object. When `null`, the `network_security_custom_endpoint` field will be omitted from the resulting object.\n  - `network_services_custom_endpoint` (`string`): Set the `network_services_custom_endpoint` field on the resulting object. When `null`, the `network_services_custom_endpoint` field will be omitted from the resulting object.\n  - `notebooks_custom_endpoint` (`string`): Set the `notebooks_custom_endpoint` field on the resulting object. When `null`, the `notebooks_custom_endpoint` field will be omitted from the resulting object.\n  - `org_policy_custom_endpoint` (`string`): Set the `org_policy_custom_endpoint` field on the resulting object. When `null`, the `org_policy_custom_endpoint` field will be omitted from the resulting object.\n  - `os_config_custom_endpoint` (`string`): Set the `os_config_custom_endpoint` field on the resulting object. When `null`, the `os_config_custom_endpoint` field will be omitted from the resulting object.\n  - `os_login_custom_endpoint` (`string`): Set the `os_login_custom_endpoint` field on the resulting object. When `null`, the `os_login_custom_endpoint` field will be omitted from the resulting object.\n  - `privateca_custom_endpoint` (`string`): Set the `privateca_custom_endpoint` field on the resulting object. When `null`, the `privateca_custom_endpoint` field will be omitted from the resulting object.\n  - `project` (`string`): Set the `project` field on the resulting object. When `null`, the `project` field will be omitted from the resulting object.\n  - `public_ca_custom_endpoint` (`string`): Set the `public_ca_custom_endpoint` field on the resulting object. When `null`, the `public_ca_custom_endpoint` field will be omitted from the resulting object.\n  - `pubsub_custom_endpoint` (`string`): Set the `pubsub_custom_endpoint` field on the resulting object. When `null`, the `pubsub_custom_endpoint` field will be omitted from the resulting object.\n  - `pubsub_lite_custom_endpoint` (`string`): Set the `pubsub_lite_custom_endpoint` field on the resulting object. When `null`, the `pubsub_lite_custom_endpoint` field will be omitted from the resulting object.\n  - `recaptcha_enterprise_custom_endpoint` (`string`): Set the `recaptcha_enterprise_custom_endpoint` field on the resulting object. When `null`, the `recaptcha_enterprise_custom_endpoint` field will be omitted from the resulting object.\n  - `redis_custom_endpoint` (`string`): Set the `redis_custom_endpoint` field on the resulting object. When `null`, the `redis_custom_endpoint` field will be omitted from the resulting object.\n  - `region` (`string`): Set the `region` field on the resulting object. When `null`, the `region` field will be omitted from the resulting object.\n  - `request_reason` (`string`): Set the `request_reason` field on the resulting object. When `null`, the `request_reason` field will be omitted from the resulting object.\n  - `request_timeout` (`string`): Set the `request_timeout` field on the resulting object. When `null`, the `request_timeout` field will be omitted from the resulting object.\n  - `resource_manager_custom_endpoint` (`string`): Set the `resource_manager_custom_endpoint` field on the resulting object. When `null`, the `resource_manager_custom_endpoint` field will be omitted from the resulting object.\n  - `resource_manager_v3_custom_endpoint` (`string`): Set the `resource_manager_v3_custom_endpoint` field on the resulting object. When `null`, the `resource_manager_v3_custom_endpoint` field will be omitted from the resulting object.\n  - `scopes` (`list`): Set the `scopes` field on the resulting object. When `null`, the `scopes` field will be omitted from the resulting object.\n  - `secret_manager_custom_endpoint` (`string`): Set the `secret_manager_custom_endpoint` field on the resulting object. When `null`, the `secret_manager_custom_endpoint` field will be omitted from the resulting object.\n  - `security_center_custom_endpoint` (`string`): Set the `security_center_custom_endpoint` field on the resulting object. When `null`, the `security_center_custom_endpoint` field will be omitted from the resulting object.\n  - `service_management_custom_endpoint` (`string`): Set the `service_management_custom_endpoint` field on the resulting object. When `null`, the `service_management_custom_endpoint` field will be omitted from the resulting object.\n  - `service_networking_custom_endpoint` (`string`): Set the `service_networking_custom_endpoint` field on the resulting object. When `null`, the `service_networking_custom_endpoint` field will be omitted from the resulting object.\n  - `service_usage_custom_endpoint` (`string`): Set the `service_usage_custom_endpoint` field on the resulting object. When `null`, the `service_usage_custom_endpoint` field will be omitted from the resulting object.\n  - `source_repo_custom_endpoint` (`string`): Set the `source_repo_custom_endpoint` field on the resulting object. When `null`, the `source_repo_custom_endpoint` field will be omitted from the resulting object.\n  - `spanner_custom_endpoint` (`string`): Set the `spanner_custom_endpoint` field on the resulting object. When `null`, the `spanner_custom_endpoint` field will be omitted from the resulting object.\n  - `sql_custom_endpoint` (`string`): Set the `sql_custom_endpoint` field on the resulting object. When `null`, the `sql_custom_endpoint` field will be omitted from the resulting object.\n  - `storage_custom_endpoint` (`string`): Set the `storage_custom_endpoint` field on the resulting object. When `null`, the `storage_custom_endpoint` field will be omitted from the resulting object.\n  - `storage_insights_custom_endpoint` (`string`): Set the `storage_insights_custom_endpoint` field on the resulting object. When `null`, the `storage_insights_custom_endpoint` field will be omitted from the resulting object.\n  - `storage_transfer_custom_endpoint` (`string`): Set the `storage_transfer_custom_endpoint` field on the resulting object. When `null`, the `storage_transfer_custom_endpoint` field will be omitted from the resulting object.\n  - `tags_custom_endpoint` (`string`): Set the `tags_custom_endpoint` field on the resulting object. When `null`, the `tags_custom_endpoint` field will be omitted from the resulting object.\n  - `tags_location_custom_endpoint` (`string`): Set the `tags_location_custom_endpoint` field on the resulting object. When `null`, the `tags_location_custom_endpoint` field will be omitted from the resulting object.\n  - `tpu_custom_endpoint` (`string`): Set the `tpu_custom_endpoint` field on the resulting object. When `null`, the `tpu_custom_endpoint` field will be omitted from the resulting object.\n  - `universe_domain` (`string`): Set the `universe_domain` field on the resulting object. When `null`, the `universe_domain` field will be omitted from the resulting object.\n  - `user_project_override` (`bool`): Set the `user_project_override` field on the resulting object. When `null`, the `user_project_override` field will be omitted from the resulting object.\n  - `vertex_ai_custom_endpoint` (`string`): Set the `vertex_ai_custom_endpoint` field on the resulting object. When `null`, the `vertex_ai_custom_endpoint` field will be omitted from the resulting object.\n  - `vmwareengine_custom_endpoint` (`string`): Set the `vmwareengine_custom_endpoint` field on the resulting object. When `null`, the `vmwareengine_custom_endpoint` field will be omitted from the resulting object.\n  - `vpc_access_custom_endpoint` (`string`): Set the `vpc_access_custom_endpoint` field on the resulting object. When `null`, the `vpc_access_custom_endpoint` field will be omitted from the resulting object.\n  - `workflows_custom_endpoint` (`string`): Set the `workflows_custom_endpoint` field on the resulting object. When `null`, the `workflows_custom_endpoint` field will be omitted from the resulting object.\n  - `zone` (`string`): Set the `zone` field on the resulting object. When `null`, the `zone` field will be omitted from the resulting object.\n  - `batching` (`list[obj]`): Set the `batching` field on the resulting object. When `null`, the `batching` sub block will be omitted from the resulting object. When setting the sub block, it is recommended to construct the object using the [google.provider.batching.new](#fn-googlebatchingnew) constructor.\n\n**Returns**:\n  - An attribute object that can be used with [tf.withProvider](https://github.com/tf-libsonnet/core/tree/main/docs#fn-withprovider) to construct a new `google` provider\n  configuration into the root Terraform configuration.\n', args=[]),
  newAttrs(
    access_approval_custom_endpoint=null,
    access_context_manager_custom_endpoint=null,
    access_token=null,
    active_directory_custom_endpoint=null,
    alloydb_custom_endpoint=null,
    apigee_custom_endpoint=null,
    apikeys_custom_endpoint=null,
    app_engine_custom_endpoint=null,
    artifact_registry_custom_endpoint=null,
    assured_workloads_custom_endpoint=null,
    batching=null,
    beyondcorp_custom_endpoint=null,
    big_query_custom_endpoint=null,
    biglake_custom_endpoint=null,
    bigquery_analytics_hub_custom_endpoint=null,
    bigquery_connection_custom_endpoint=null,
    bigquery_data_transfer_custom_endpoint=null,
    bigquery_datapolicy_custom_endpoint=null,
    bigquery_reservation_custom_endpoint=null,
    bigtable_custom_endpoint=null,
    billing_custom_endpoint=null,
    billing_project=null,
    binary_authorization_custom_endpoint=null,
    certificate_manager_custom_endpoint=null,
    cloud_asset_custom_endpoint=null,
    cloud_billing_custom_endpoint=null,
    cloud_build_custom_endpoint=null,
    cloud_build_worker_pool_custom_endpoint=null,
    cloud_functions_custom_endpoint=null,
    cloud_identity_custom_endpoint=null,
    cloud_ids_custom_endpoint=null,
    cloud_resource_manager_custom_endpoint=null,
    cloud_run_custom_endpoint=null,
    cloud_run_v2_custom_endpoint=null,
    cloud_scheduler_custom_endpoint=null,
    cloud_tasks_custom_endpoint=null,
    cloudbuildv2_custom_endpoint=null,
    clouddeploy_custom_endpoint=null,
    cloudfunctions2_custom_endpoint=null,
    composer_custom_endpoint=null,
    compute_custom_endpoint=null,
    container_analysis_custom_endpoint=null,
    container_attached_custom_endpoint=null,
    container_aws_custom_endpoint=null,
    container_azure_custom_endpoint=null,
    container_custom_endpoint=null,
    core_billing_custom_endpoint=null,
    credentials=null,
    data_catalog_custom_endpoint=null,
    data_fusion_custom_endpoint=null,
    data_loss_prevention_custom_endpoint=null,
    data_pipeline_custom_endpoint=null,
    database_migration_service_custom_endpoint=null,
    dataflow_custom_endpoint=null,
    dataplex_custom_endpoint=null,
    dataproc_custom_endpoint=null,
    dataproc_metastore_custom_endpoint=null,
    datastore_custom_endpoint=null,
    datastream_custom_endpoint=null,
    default_labels=null,
    deployment_manager_custom_endpoint=null,
    dialogflow_custom_endpoint=null,
    dialogflow_cx_custom_endpoint=null,
    dns_custom_endpoint=null,
    document_ai_custom_endpoint=null,
    document_ai_warehouse_custom_endpoint=null,
    edgecontainer_custom_endpoint=null,
    edgenetwork_custom_endpoint=null,
    essential_contacts_custom_endpoint=null,
    eventarc_custom_endpoint=null,
    filestore_custom_endpoint=null,
    firebaserules_custom_endpoint=null,
    firestore_custom_endpoint=null,
    gke_backup_custom_endpoint=null,
    gke_hub2_custom_endpoint=null,
    gke_hub_custom_endpoint=null,
    gkehub_feature_custom_endpoint=null,
    gkeonprem_custom_endpoint=null,
    healthcare_custom_endpoint=null,
    iam2_custom_endpoint=null,
    iam_beta_custom_endpoint=null,
    iam_credentials_custom_endpoint=null,
    iam_custom_endpoint=null,
    iam_workforce_pool_custom_endpoint=null,
    iap_custom_endpoint=null,
    identity_platform_custom_endpoint=null,
    impersonate_service_account=null,
    impersonate_service_account_delegates=null,
    integration_connectors_custom_endpoint=null,
    kms_custom_endpoint=null,
    logging_custom_endpoint=null,
    looker_custom_endpoint=null,
    memcache_custom_endpoint=null,
    migration_center_custom_endpoint=null,
    ml_engine_custom_endpoint=null,
    monitoring_custom_endpoint=null,
    netapp_custom_endpoint=null,
    network_connectivity_custom_endpoint=null,
    network_management_custom_endpoint=null,
    network_security_custom_endpoint=null,
    network_services_custom_endpoint=null,
    notebooks_custom_endpoint=null,
    org_policy_custom_endpoint=null,
    os_config_custom_endpoint=null,
    os_login_custom_endpoint=null,
    privateca_custom_endpoint=null,
    project=null,
    public_ca_custom_endpoint=null,
    pubsub_custom_endpoint=null,
    pubsub_lite_custom_endpoint=null,
    recaptcha_enterprise_custom_endpoint=null,
    redis_custom_endpoint=null,
    region=null,
    request_reason=null,
    request_timeout=null,
    resource_manager_custom_endpoint=null,
    resource_manager_v3_custom_endpoint=null,
    scopes=null,
    secret_manager_custom_endpoint=null,
    security_center_custom_endpoint=null,
    service_management_custom_endpoint=null,
    service_networking_custom_endpoint=null,
    service_usage_custom_endpoint=null,
    source_repo_custom_endpoint=null,
    spanner_custom_endpoint=null,
    sql_custom_endpoint=null,
    storage_custom_endpoint=null,
    storage_insights_custom_endpoint=null,
    storage_transfer_custom_endpoint=null,
    tags_custom_endpoint=null,
    tags_location_custom_endpoint=null,
    tpu_custom_endpoint=null,
    universe_domain=null,
    user_project_override=null,
    vertex_ai_custom_endpoint=null,
    vmwareengine_custom_endpoint=null,
    vpc_access_custom_endpoint=null,
    workflows_custom_endpoint=null,
    zone=null
  ):: std.prune(a={
    access_approval_custom_endpoint: access_approval_custom_endpoint,
    access_context_manager_custom_endpoint: access_context_manager_custom_endpoint,
    access_token: access_token,
    active_directory_custom_endpoint: active_directory_custom_endpoint,
    alloydb_custom_endpoint: alloydb_custom_endpoint,
    apigee_custom_endpoint: apigee_custom_endpoint,
    apikeys_custom_endpoint: apikeys_custom_endpoint,
    app_engine_custom_endpoint: app_engine_custom_endpoint,
    artifact_registry_custom_endpoint: artifact_registry_custom_endpoint,
    assured_workloads_custom_endpoint: assured_workloads_custom_endpoint,
    batching: batching,
    beyondcorp_custom_endpoint: beyondcorp_custom_endpoint,
    big_query_custom_endpoint: big_query_custom_endpoint,
    biglake_custom_endpoint: biglake_custom_endpoint,
    bigquery_analytics_hub_custom_endpoint: bigquery_analytics_hub_custom_endpoint,
    bigquery_connection_custom_endpoint: bigquery_connection_custom_endpoint,
    bigquery_data_transfer_custom_endpoint: bigquery_data_transfer_custom_endpoint,
    bigquery_datapolicy_custom_endpoint: bigquery_datapolicy_custom_endpoint,
    bigquery_reservation_custom_endpoint: bigquery_reservation_custom_endpoint,
    bigtable_custom_endpoint: bigtable_custom_endpoint,
    billing_custom_endpoint: billing_custom_endpoint,
    billing_project: billing_project,
    binary_authorization_custom_endpoint: binary_authorization_custom_endpoint,
    certificate_manager_custom_endpoint: certificate_manager_custom_endpoint,
    cloud_asset_custom_endpoint: cloud_asset_custom_endpoint,
    cloud_billing_custom_endpoint: cloud_billing_custom_endpoint,
    cloud_build_custom_endpoint: cloud_build_custom_endpoint,
    cloud_build_worker_pool_custom_endpoint: cloud_build_worker_pool_custom_endpoint,
    cloud_functions_custom_endpoint: cloud_functions_custom_endpoint,
    cloud_identity_custom_endpoint: cloud_identity_custom_endpoint,
    cloud_ids_custom_endpoint: cloud_ids_custom_endpoint,
    cloud_resource_manager_custom_endpoint: cloud_resource_manager_custom_endpoint,
    cloud_run_custom_endpoint: cloud_run_custom_endpoint,
    cloud_run_v2_custom_endpoint: cloud_run_v2_custom_endpoint,
    cloud_scheduler_custom_endpoint: cloud_scheduler_custom_endpoint,
    cloud_tasks_custom_endpoint: cloud_tasks_custom_endpoint,
    cloudbuildv2_custom_endpoint: cloudbuildv2_custom_endpoint,
    clouddeploy_custom_endpoint: clouddeploy_custom_endpoint,
    cloudfunctions2_custom_endpoint: cloudfunctions2_custom_endpoint,
    composer_custom_endpoint: composer_custom_endpoint,
    compute_custom_endpoint: compute_custom_endpoint,
    container_analysis_custom_endpoint: container_analysis_custom_endpoint,
    container_attached_custom_endpoint: container_attached_custom_endpoint,
    container_aws_custom_endpoint: container_aws_custom_endpoint,
    container_azure_custom_endpoint: container_azure_custom_endpoint,
    container_custom_endpoint: container_custom_endpoint,
    core_billing_custom_endpoint: core_billing_custom_endpoint,
    credentials: credentials,
    data_catalog_custom_endpoint: data_catalog_custom_endpoint,
    data_fusion_custom_endpoint: data_fusion_custom_endpoint,
    data_loss_prevention_custom_endpoint: data_loss_prevention_custom_endpoint,
    data_pipeline_custom_endpoint: data_pipeline_custom_endpoint,
    database_migration_service_custom_endpoint: database_migration_service_custom_endpoint,
    dataflow_custom_endpoint: dataflow_custom_endpoint,
    dataplex_custom_endpoint: dataplex_custom_endpoint,
    dataproc_custom_endpoint: dataproc_custom_endpoint,
    dataproc_metastore_custom_endpoint: dataproc_metastore_custom_endpoint,
    datastore_custom_endpoint: datastore_custom_endpoint,
    datastream_custom_endpoint: datastream_custom_endpoint,
    default_labels: default_labels,
    deployment_manager_custom_endpoint: deployment_manager_custom_endpoint,
    dialogflow_custom_endpoint: dialogflow_custom_endpoint,
    dialogflow_cx_custom_endpoint: dialogflow_cx_custom_endpoint,
    dns_custom_endpoint: dns_custom_endpoint,
    document_ai_custom_endpoint: document_ai_custom_endpoint,
    document_ai_warehouse_custom_endpoint: document_ai_warehouse_custom_endpoint,
    edgecontainer_custom_endpoint: edgecontainer_custom_endpoint,
    edgenetwork_custom_endpoint: edgenetwork_custom_endpoint,
    essential_contacts_custom_endpoint: essential_contacts_custom_endpoint,
    eventarc_custom_endpoint: eventarc_custom_endpoint,
    filestore_custom_endpoint: filestore_custom_endpoint,
    firebaserules_custom_endpoint: firebaserules_custom_endpoint,
    firestore_custom_endpoint: firestore_custom_endpoint,
    gke_backup_custom_endpoint: gke_backup_custom_endpoint,
    gke_hub2_custom_endpoint: gke_hub2_custom_endpoint,
    gke_hub_custom_endpoint: gke_hub_custom_endpoint,
    gkehub_feature_custom_endpoint: gkehub_feature_custom_endpoint,
    gkeonprem_custom_endpoint: gkeonprem_custom_endpoint,
    healthcare_custom_endpoint: healthcare_custom_endpoint,
    iam2_custom_endpoint: iam2_custom_endpoint,
    iam_beta_custom_endpoint: iam_beta_custom_endpoint,
    iam_credentials_custom_endpoint: iam_credentials_custom_endpoint,
    iam_custom_endpoint: iam_custom_endpoint,
    iam_workforce_pool_custom_endpoint: iam_workforce_pool_custom_endpoint,
    iap_custom_endpoint: iap_custom_endpoint,
    identity_platform_custom_endpoint: identity_platform_custom_endpoint,
    impersonate_service_account: impersonate_service_account,
    impersonate_service_account_delegates: impersonate_service_account_delegates,
    integration_connectors_custom_endpoint: integration_connectors_custom_endpoint,
    kms_custom_endpoint: kms_custom_endpoint,
    logging_custom_endpoint: logging_custom_endpoint,
    looker_custom_endpoint: looker_custom_endpoint,
    memcache_custom_endpoint: memcache_custom_endpoint,
    migration_center_custom_endpoint: migration_center_custom_endpoint,
    ml_engine_custom_endpoint: ml_engine_custom_endpoint,
    monitoring_custom_endpoint: monitoring_custom_endpoint,
    netapp_custom_endpoint: netapp_custom_endpoint,
    network_connectivity_custom_endpoint: network_connectivity_custom_endpoint,
    network_management_custom_endpoint: network_management_custom_endpoint,
    network_security_custom_endpoint: network_security_custom_endpoint,
    network_services_custom_endpoint: network_services_custom_endpoint,
    notebooks_custom_endpoint: notebooks_custom_endpoint,
    org_policy_custom_endpoint: org_policy_custom_endpoint,
    os_config_custom_endpoint: os_config_custom_endpoint,
    os_login_custom_endpoint: os_login_custom_endpoint,
    privateca_custom_endpoint: privateca_custom_endpoint,
    project: project,
    public_ca_custom_endpoint: public_ca_custom_endpoint,
    pubsub_custom_endpoint: pubsub_custom_endpoint,
    pubsub_lite_custom_endpoint: pubsub_lite_custom_endpoint,
    recaptcha_enterprise_custom_endpoint: recaptcha_enterprise_custom_endpoint,
    redis_custom_endpoint: redis_custom_endpoint,
    region: region,
    request_reason: request_reason,
    request_timeout: request_timeout,
    resource_manager_custom_endpoint: resource_manager_custom_endpoint,
    resource_manager_v3_custom_endpoint: resource_manager_v3_custom_endpoint,
    scopes: scopes,
    secret_manager_custom_endpoint: secret_manager_custom_endpoint,
    security_center_custom_endpoint: security_center_custom_endpoint,
    service_management_custom_endpoint: service_management_custom_endpoint,
    service_networking_custom_endpoint: service_networking_custom_endpoint,
    service_usage_custom_endpoint: service_usage_custom_endpoint,
    source_repo_custom_endpoint: source_repo_custom_endpoint,
    spanner_custom_endpoint: spanner_custom_endpoint,
    sql_custom_endpoint: sql_custom_endpoint,
    storage_custom_endpoint: storage_custom_endpoint,
    storage_insights_custom_endpoint: storage_insights_custom_endpoint,
    storage_transfer_custom_endpoint: storage_transfer_custom_endpoint,
    tags_custom_endpoint: tags_custom_endpoint,
    tags_location_custom_endpoint: tags_location_custom_endpoint,
    tpu_custom_endpoint: tpu_custom_endpoint,
    universe_domain: universe_domain,
    user_project_override: user_project_override,
    vertex_ai_custom_endpoint: vertex_ai_custom_endpoint,
    vmwareengine_custom_endpoint: vmwareengine_custom_endpoint,
    vpc_access_custom_endpoint: vpc_access_custom_endpoint,
    workflows_custom_endpoint: workflows_custom_endpoint,
    zone: zone,
  }),
  batching:: {
    '#new':: d.fn(help='\n`google.batching.new` constructs a new object with attributes and blocks configured for the `batching`\nTerraform sub block.\n\n\n\n**Args**:\n  - `enable_batching` (`bool`): Set the `enable_batching` field on the resulting object. When `null`, the `enable_batching` field will be omitted from the resulting object.\n  - `send_after` (`string`): Set the `send_after` field on the resulting object. When `null`, the `send_after` field will be omitted from the resulting object.\n\n**Returns**:\n  - An attribute object that represents the `batching` sub block.\n', args=[]),
    new(
      enable_batching=null,
      send_after=null
    ):: std.prune(a={
      enable_batching: enable_batching,
      send_after: send_after,
    }),
  },
}
